if(EXISTS "/Users/danielwendt/Projects/c++/unit_converter/tests/tests[1]_tests.cmake")
  include("/Users/danielwendt/Projects/c++/unit_converter/tests/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
